server:
  port: 8080
  context-path: /spring-jpa
com:
  jin:
    datasource:
      master:
        dataSourceProperties:
          user: root
          password: 123456
          serverName: mysql-master
          portNumber: 3306
          databaseName: test          
        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        connectionTimeout: 2000
        poolName: masterPool
        maximumPoolSize: 10
      slave:
        dataSourceProperties:
          user: root
          password: 123456
          serverName: mysql-slave
          portNumber: 3306
          databaseName: test
        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        connectionTimeout: 2000
        poolName: slavePool
        maximumPoolSize: 20
spring:
  application:
    name: spring-jpa
  jpa:
    database-platform:
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  file: ./target/spring-jpa.log