server:
  port: 8080
  context-path: /spring-jpa
com:
  jin:
    datasource:
      master:
        dataSourceProperties:
          user: zuojin
          password: 123456
          serverName: localhost
          portNumber: 7432
          databaseName: test          
        dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
        connectionTimeout: 2000
        poolName: masterPool
        maximumPoolSize: 10
      slave:
        dataSourceProperties:
          user: zuojin
          password: 123456
          serverName: localhost
          portNumber: 8432
          databaseName: test
        dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
        connectionTimeout: 2000
        poolName: slavePool
        maximumPoolSize: 20
spring:
  application:
    name: spring-jpa
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  file: ./target/spring-jpa.log